/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IArtefactRegistry, IArtefactRegistryInterface } from "../../interfaces/IArtefactRegistry.js";

  const _abi = [
  {
    "inputs": [],
    "name": "ArtefactAlreadyExists",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "artefactId",
        "type": "bytes32"
      }
    ],
    "name": "ArtefactNotFound",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "artefactId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "address",
        "name": "creator",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "snapshotCommitment",
        "type": "bytes32"
      }
    ],
    "name": "ArtefactCommitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "artefactId",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "enum VerificationStatus",
        "name": "status",
        "type": "uint8"
      }
    ],
    "name": "ArtefactVerified",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "snapshotCommitment",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "eligibilityNonce",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "policyReference",
        "type": "bytes32"
      },
      {
        "internalType": "string",
        "name": "contentReference",
        "type": "string"
      }
    ],
    "name": "commitArtefact",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "artefactId",
        "type": "bytes32"
      }
    ],
    "name": "getArtefact",
    "outputs": [
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "artefactId",
            "type": "bytes32"
          },
          {
            "internalType": "address",
            "name": "creator",
            "type": "address"
          },
          {
            "internalType": "bytes32",
            "name": "snapshotCommitment",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "eligibilityNonce",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "policyReference",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "timestamp",
            "type": "uint256"
          },
          {
            "internalType": "string",
            "name": "contentReference",
            "type": "string"
          }
        ],
        "internalType": "struct Artefact",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "creator",
        "type": "address"
      }
    ],
    "name": "getArtefactsByCreator",
    "outputs": [
      {
        "internalType": "bytes32[]",
        "name": "",
        "type": "bytes32[]"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "artefactId",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "snapshotCommitment",
        "type": "bytes32"
      }
    ],
    "name": "verifyArtefact",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IArtefactRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IArtefactRegistryInterface {
      return new Interface(_abi) as IArtefactRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IArtefactRegistry {
      return new Contract(address, _abi, runner) as unknown as IArtefactRegistry;
    }
  }
  