/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IEligibilityRegistry, IEligibilityRegistryInterface } from "../../interfaces/IEligibilityRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "EligibilityAlreadyActive",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "EligibilityExpiredError",
    "type": "error"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "EligibilityNotFound",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "UnauthorizedRegistrar",
    "type": "error"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "nonce",
        "type": "uint256"
      }
    ],
    "name": "EligibilityExpired",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "nonce",
        "type": "uint256"
      }
    ],
    "name": "EligibilityRegistered",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "nonce",
        "type": "uint256"
      }
    ],
    "name": "EligibilityRevoked",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "getEligibility",
    "outputs": [
      {
        "components": [
          {
            "internalType": "address",
            "name": "borrower",
            "type": "address"
          },
          {
            "internalType": "enum RiskTier",
            "name": "riskTier",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "maxActiveCredit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "maxLtvBps",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validUntil",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "policyVersion",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "evidenceCommitment",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32",
            "name": "attestcoinContext",
            "type": "bytes32"
          },
          {
            "internalType": "uint256",
            "name": "nonce",
            "type": "uint256"
          },
          {
            "internalType": "bool",
            "name": "active",
            "type": "bool"
          }
        ],
        "internalType": "struct Eligibility",
        "name": "",
        "type": "tuple"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "getEligibilityNonce",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "isEligibilityValid",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "enum RiskTier",
            "name": "riskTier",
            "type": "uint8"
          },
          {
            "internalType": "uint256",
            "name": "maxActiveCredit",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "maxLtvBps",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "validUntil",
            "type": "uint256"
          },
          {
            "internalType": "uint256",
            "name": "policyVersion",
            "type": "uint256"
          },
          {
            "internalType": "bytes32",
            "name": "evidenceCommitment",
            "type": "bytes32"
          }
        ],
        "internalType": "struct EligibilityParams",
        "name": "params",
        "type": "tuple"
      },
      {
        "internalType": "uint8",
        "name": "v",
        "type": "uint8"
      },
      {
        "internalType": "bytes32",
        "name": "r",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "s",
        "type": "bytes32"
      },
      {
        "components": [
          {
            "internalType": "uint64",
            "name": "chainKey",
            "type": "uint64"
          },
          {
            "internalType": "uint64",
            "name": "headerNumber",
            "type": "uint64"
          },
          {
            "internalType": "bytes",
            "name": "txBytes",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "merkleProof",
            "type": "bytes"
          },
          {
            "internalType": "bytes",
            "name": "continuityProof",
            "type": "bytes"
          }
        ],
        "internalType": "struct AttestcoinProof",
        "name": "proof",
        "type": "tuple"
      }
    ],
    "name": "registerEligibility",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "borrower",
        "type": "address"
      }
    ],
    "name": "revokeEligibility",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IEligibilityRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IEligibilityRegistryInterface {
      return new Interface(_abi) as IEligibilityRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IEligibilityRegistry {
      return new Contract(address, _abi, runner) as unknown as IEligibilityRegistry;
    }
  }
  