/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type EligibilityStruct = {borrower: AddressLike, riskTier: BigNumberish, maxActiveCredit: BigNumberish, maxLtvBps: BigNumberish, validUntil: BigNumberish, policyVersion: BigNumberish, evidenceCommitment: BytesLike, attestcoinContext: BytesLike, nonce: BigNumberish, active: boolean}

    export type EligibilityStructOutput = [borrower: string, riskTier: bigint, maxActiveCredit: bigint, maxLtvBps: bigint, validUntil: bigint, policyVersion: bigint, evidenceCommitment: string, attestcoinContext: string, nonce: bigint, active: boolean] & {borrower: string, riskTier: bigint, maxActiveCredit: bigint, maxLtvBps: bigint, validUntil: bigint, policyVersion: bigint, evidenceCommitment: string, attestcoinContext: string, nonce: bigint, active: boolean }
  

    export type EligibilityParamsStruct = {riskTier: BigNumberish, maxActiveCredit: BigNumberish, maxLtvBps: BigNumberish, validUntil: BigNumberish, policyVersion: BigNumberish, evidenceCommitment: BytesLike}

    export type EligibilityParamsStructOutput = [riskTier: bigint, maxActiveCredit: bigint, maxLtvBps: bigint, validUntil: bigint, policyVersion: bigint, evidenceCommitment: string] & {riskTier: bigint, maxActiveCredit: bigint, maxLtvBps: bigint, validUntil: bigint, policyVersion: bigint, evidenceCommitment: string }
  

    export type AttestcoinProofStruct = {chainKey: BigNumberish, headerNumber: BigNumberish, txBytes: BytesLike, merkleProof: BytesLike, continuityProof: BytesLike}

    export type AttestcoinProofStructOutput = [chainKey: bigint, headerNumber: bigint, txBytes: string, merkleProof: string, continuityProof: string] & {chainKey: bigint, headerNumber: bigint, txBytes: string, merkleProof: string, continuityProof: string }
  

  export interface EligibilityRegistryInterface extends Interface {
    getFunction(nameOrSignature: "eligibilities" | "getEligibility" | "getEligibilityNonce" | "isEligibilityValid" | "nonces" | "owner" | "paused" | "registerEligibility" | "registrar" | "renounceOwnership" | "revokeEligibility" | "setRegistrar" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "EligibilityExpired" | "EligibilityRegistered" | "EligibilityRevoked" | "OwnershipTransferred" | "Paused" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'eligibilities', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEligibility', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getEligibilityNonce', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isEligibilityValid', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'nonces', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'registerEligibility', values: [EligibilityParamsStruct, BigNumberish, BytesLike, BytesLike, AttestcoinProofStruct]): string;
encodeFunctionData(functionFragment: 'registrar', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeEligibility', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRegistrar', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'eligibilities', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEligibilityNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEligibilityValid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonces', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registerEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registrar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeEligibility', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRegistrar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace EligibilityExpiredEvent {
      export type InputTuple = [borrower: AddressLike, nonce: BigNumberish];
      export type OutputTuple = [borrower: string, nonce: bigint];
      export interface OutputObject {borrower: string, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EligibilityRegisteredEvent {
      export type InputTuple = [borrower: AddressLike, nonce: BigNumberish];
      export type OutputTuple = [borrower: string, nonce: bigint];
      export interface OutputObject {borrower: string, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EligibilityRevokedEvent {
      export type InputTuple = [borrower: AddressLike, nonce: BigNumberish];
      export type OutputTuple = [borrower: string, nonce: bigint];
      export interface OutputObject {borrower: string, nonce: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface EligibilityRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): EligibilityRegistry;
    waitForDeployment(): Promise<this>;

    interface: EligibilityRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    eligibilities: TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, string, string, bigint, boolean] & {borrower: string, riskTier: bigint, maxActiveCredit: bigint, maxLtvBps: bigint, validUntil: bigint, policyVersion: bigint, evidenceCommitment: string, attestcoinContext: string, nonce: bigint, active: boolean }],
      'view'
    >
    

    
    getEligibility: TypedContractMethod<
      [borrower: AddressLike, ],
      [EligibilityStructOutput],
      'view'
    >
    

    
    getEligibilityNonce: TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    isEligibilityValid: TypedContractMethod<
      [borrower: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    nonces: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    registerEligibility: TypedContractMethod<
      [params: EligibilityParamsStruct, v: BigNumberish, r: BytesLike, s: BytesLike, proof: AttestcoinProofStruct, ],
      [void],
      'nonpayable'
    >
    

    
    registrar: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeEligibility: TypedContractMethod<
      [borrower: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRegistrar: TypedContractMethod<
      [_registrar: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'eligibilities'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[string, bigint, bigint, bigint, bigint, bigint, string, string, bigint, boolean] & {borrower: string, riskTier: bigint, maxActiveCredit: bigint, maxLtvBps: bigint, validUntil: bigint, policyVersion: bigint, evidenceCommitment: string, attestcoinContext: string, nonce: bigint, active: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'getEligibility'): TypedContractMethod<
      [borrower: AddressLike, ],
      [EligibilityStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getEligibilityNonce'): TypedContractMethod<
      [borrower: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isEligibilityValid'): TypedContractMethod<
      [borrower: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'nonces'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'registerEligibility'): TypedContractMethod<
      [params: EligibilityParamsStruct, v: BigNumberish, r: BytesLike, s: BytesLike, proof: AttestcoinProofStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registrar'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeEligibility'): TypedContractMethod<
      [borrower: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRegistrar'): TypedContractMethod<
      [_registrar: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'EligibilityExpired'): TypedContractEvent<EligibilityExpiredEvent.InputTuple, EligibilityExpiredEvent.OutputTuple, EligibilityExpiredEvent.OutputObject>;
getEvent(key: 'EligibilityRegistered'): TypedContractEvent<EligibilityRegisteredEvent.InputTuple, EligibilityRegisteredEvent.OutputTuple, EligibilityRegisteredEvent.OutputObject>;
getEvent(key: 'EligibilityRevoked'): TypedContractEvent<EligibilityRevokedEvent.InputTuple, EligibilityRevokedEvent.OutputTuple, EligibilityRevokedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'EligibilityExpired(address,uint256)': TypedContractEvent<EligibilityExpiredEvent.InputTuple, EligibilityExpiredEvent.OutputTuple, EligibilityExpiredEvent.OutputObject>;
      EligibilityExpired: TypedContractEvent<EligibilityExpiredEvent.InputTuple, EligibilityExpiredEvent.OutputTuple, EligibilityExpiredEvent.OutputObject>;
    

      'EligibilityRegistered(address,uint256)': TypedContractEvent<EligibilityRegisteredEvent.InputTuple, EligibilityRegisteredEvent.OutputTuple, EligibilityRegisteredEvent.OutputObject>;
      EligibilityRegistered: TypedContractEvent<EligibilityRegisteredEvent.InputTuple, EligibilityRegisteredEvent.OutputTuple, EligibilityRegisteredEvent.OutputObject>;
    

      'EligibilityRevoked(address,uint256)': TypedContractEvent<EligibilityRevokedEvent.InputTuple, EligibilityRevokedEvent.OutputTuple, EligibilityRevokedEvent.OutputObject>;
      EligibilityRevoked: TypedContractEvent<EligibilityRevokedEvent.InputTuple, EligibilityRevokedEvent.OutputTuple, EligibilityRevokedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }