/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type LoanStruct = {loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish, aprBps: BigNumberish, startTime: BigNumberish, duration: BigNumberish, collateralAmount: BigNumberish, repaidAmount: BigNumberish, status: BigNumberish}

    export type LoanStructOutput = [loanId: bigint, borrower: string, lender: string, principal: bigint, aprBps: bigint, startTime: bigint, duration: bigint, collateralAmount: bigint, repaidAmount: bigint, status: bigint] & {loanId: bigint, borrower: string, lender: string, principal: bigint, aprBps: bigint, startTime: bigint, duration: bigint, collateralAmount: bigint, repaidAmount: bigint, status: bigint }
  

  export interface LoanVaultInterface extends Interface {
    getFunction(nameOrSignature: "DEFAULT_GRACE_PERIOD" | "calculateInterest" | "calculateTotalOwed" | "capacityManager" | "declareDefault" | "getLoan" | "loans" | "marketplace" | "nextLoanId" | "originateLoan" | "owner" | "paused" | "renounceOwnership" | "repayLoan" | "repaymentRegistry" | "setMarketplace" | "setRepaymentRegistry" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CollateralSeized" | "LoanDefaulted" | "LoanOriginated" | "LoanRepaid" | "OwnershipTransferred" | "Paused" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'DEFAULT_GRACE_PERIOD', values?: undefined): string;
encodeFunctionData(functionFragment: 'calculateInterest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateTotalOwed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'capacityManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'declareDefault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'loans', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'marketplace', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextLoanId', values?: undefined): string;
encodeFunctionData(functionFragment: 'originateLoan', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'repayLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'repaymentRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMarketplace', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setRepaymentRegistry', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'DEFAULT_GRACE_PERIOD', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateInterest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateTotalOwed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'capacityManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'declareDefault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loans', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'marketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextLoanId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'originateLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repaymentRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMarketplace', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRepaymentRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace CollateralSeizedEvent {
      export type InputTuple = [loanId: BigNumberish, lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, lender: string, amount: bigint];
      export interface OutputObject {loanId: bigint, lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanDefaultedEvent {
      export type InputTuple = [loanId: BigNumberish];
      export type OutputTuple = [loanId: bigint];
      export interface OutputObject {loanId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanOriginatedEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, lender: string, principal: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, lender: string, principal: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [loanId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, amount: bigint];
      export interface OutputObject {loanId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LoanVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): LoanVault;
    waitForDeployment(): Promise<this>;

    interface: LoanVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    DEFAULT_GRACE_PERIOD: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    calculateInterest: TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calculateTotalOwed: TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    capacityManager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    declareDefault: TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [LoanStructOutput],
      'view'
    >
    

    
    loans: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {loanId: bigint, borrower: string, lender: string, principal: bigint, aprBps: bigint, startTime: bigint, duration: bigint, collateralAmount: bigint, repaidAmount: bigint, status: bigint }],
      'view'
    >
    

    
    marketplace: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    nextLoanId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    originateLoan: TypedContractMethod<
      [borrower: AddressLike, lender: AddressLike, principal: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    repayLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    repaymentRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMarketplace: TypedContractMethod<
      [_marketplace: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setRepaymentRegistry: TypedContractMethod<
      [_repaymentRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'DEFAULT_GRACE_PERIOD'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateInterest'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateTotalOwed'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'capacityManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'declareDefault'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [LoanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'loans'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {loanId: bigint, borrower: string, lender: string, principal: bigint, aprBps: bigint, startTime: bigint, duration: bigint, collateralAmount: bigint, repaidAmount: bigint, status: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'marketplace'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextLoanId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'originateLoan'): TypedContractMethod<
      [borrower: AddressLike, lender: AddressLike, principal: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'repayLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'repaymentRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMarketplace'): TypedContractMethod<
      [_marketplace: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRepaymentRegistry'): TypedContractMethod<
      [_repaymentRegistry: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CollateralSeized'): TypedContractEvent<CollateralSeizedEvent.InputTuple, CollateralSeizedEvent.OutputTuple, CollateralSeizedEvent.OutputObject>;
getEvent(key: 'LoanDefaulted'): TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
getEvent(key: 'LoanOriginated'): TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'CollateralSeized(uint256,address,uint256)': TypedContractEvent<CollateralSeizedEvent.InputTuple, CollateralSeizedEvent.OutputTuple, CollateralSeizedEvent.OutputObject>;
      CollateralSeized: TypedContractEvent<CollateralSeizedEvent.InputTuple, CollateralSeizedEvent.OutputTuple, CollateralSeizedEvent.OutputObject>;
    

      'LoanDefaulted(uint256)': TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
      LoanDefaulted: TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
    

      'LoanOriginated(uint256,address,address,uint256)': TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
      LoanOriginated: TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
    

      'LoanRepaid(uint256,uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }