/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"

    export type BorrowRequestStruct = {requestId: BigNumberish, borrower: AddressLike, amount: BigNumberish, maxAprBps: BigNumberish, maxDuration: BigNumberish, collateralAmount: BigNumberish, status: BigNumberish, createdAt: BigNumberish}

    export type BorrowRequestStructOutput = [requestId: bigint, borrower: string, amount: bigint, maxAprBps: bigint, maxDuration: bigint, collateralAmount: bigint, status: bigint, createdAt: bigint] & {requestId: bigint, borrower: string, amount: bigint, maxAprBps: bigint, maxDuration: bigint, collateralAmount: bigint, status: bigint, createdAt: bigint }


    export type LenderOfferStruct = {offerId: BigNumberish, requestId: BigNumberish, lender: AddressLike, aprBps: BigNumberish, duration: BigNumberish, requiredCollateral: BigNumberish, status: BigNumberish, createdAt: BigNumberish}

    export type LenderOfferStructOutput = [offerId: bigint, requestId: bigint, lender: string, aprBps: bigint, duration: bigint, requiredCollateral: bigint, status: bigint, createdAt: bigint] & {offerId: bigint, requestId: bigint, lender: string, aprBps: bigint, duration: bigint, requiredCollateral: bigint, status: bigint, createdAt: bigint }


  export interface LoanMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "acceptOffer" | "cancelBorrowRequest" | "capacityManager" | "createBorrowRequest" | "createLenderOffer" | "eligibilityRegistry" | "getBorrowRequest" | "getLenderOffer" | "getOpenRequests" | "loanVault" | "nextOfferId" | "nextRequestId" | "offerDeposits" | "offers" | "owner" | "paused" | "renounceOwnership" | "requests" | "setLoanVault" | "transferOwnership" | "withdrawOffer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OfferAccepted" | "OfferCreated" | "OfferWithdrawn" | "OwnershipTransferred" | "Paused" | "RequestCancelled" | "RequestCreated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOffer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelBorrowRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'capacityManager', values?: undefined): string;
encodeFunctionData(functionFragment: 'createBorrowRequest', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createLenderOffer', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'eligibilityRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'getBorrowRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLenderOffer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOpenRequests', values?: undefined): string;
encodeFunctionData(functionFragment: 'loanVault', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextOfferId', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextRequestId', values?: undefined): string;
encodeFunctionData(functionFragment: 'offerDeposits', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'offers', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setLoanVault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawOffer', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acceptOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelBorrowRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'capacityManager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBorrowRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLenderOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eligibilityRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLenderOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOpenRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'loanVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextOfferId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextRequestId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'offerDeposits', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'offers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setLoanVault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawOffer', data: BytesLike): Result;
  }


    export namespace OfferAcceptedEvent {
      export type InputTuple = [offerId: BigNumberish, requestId: BigNumberish];
      export type OutputTuple = [offerId: bigint, requestId: bigint];
      export interface OutputObject {offerId: bigint, requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace OfferCreatedEvent {
      export type InputTuple = [offerId: BigNumberish, requestId: BigNumberish, lender: AddressLike];
      export type OutputTuple = [offerId: bigint, requestId: bigint, lender: string];
      export interface OutputObject {offerId: bigint, requestId: bigint, lender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace OfferWithdrawnEvent {
      export type InputTuple = [offerId: BigNumberish];
      export type OutputTuple = [offerId: bigint];
      export interface OutputObject {offerId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace RequestCancelledEvent {
      export type InputTuple = [requestId: BigNumberish];
      export type OutputTuple = [requestId: bigint];
      export interface OutputObject {requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace RequestCreatedEvent {
      export type InputTuple = [requestId: BigNumberish, borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [requestId: bigint, borrower: string, amount: bigint];
      export interface OutputObject {requestId: bigint, borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



  export interface LoanMarketplace extends BaseContract {

    connect(runner?: ContractRunner | null): LoanMarketplace;
    waitForDeployment(): Promise<this>;

    interface: LoanMarketplaceInterface;


  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>




    acceptOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'payable'
    >



    cancelBorrowRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >



    capacityManager: TypedContractMethod<
      [],
      [string],
      'view'
    >



    createBorrowRequest: TypedContractMethod<
      [amount: BigNumberish, maxAprBps: BigNumberish, maxDuration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >



    createLenderOffer: TypedContractMethod<
      [requestId: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, requiredCollateral: BigNumberish, ],
      [bigint],
      'payable'
    >



    eligibilityRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >



    getBorrowRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [BorrowRequestStructOutput],
      'view'
    >



    getLenderOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [LenderOfferStructOutput],
      'view'
    >



    getOpenRequests: TypedContractMethod<
      [],
      [BorrowRequestStructOutput[]],
      'view'
    >



    loanVault: TypedContractMethod<
      [],
      [string],
      'view'
    >



    nextOfferId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    nextRequestId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >



    offerDeposits: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >



    offers: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, bigint, bigint, bigint, bigint] & {offerId: bigint, requestId: bigint, lender: string, aprBps: bigint, duration: bigint, requiredCollateral: bigint, status: bigint, createdAt: bigint }],
      'view'
    >



    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >



    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >



    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >



    requests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {requestId: bigint, borrower: string, amount: bigint, maxAprBps: bigint, maxDuration: bigint, collateralAmount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >



    setLoanVault: TypedContractMethod<
      [_loanVault: AddressLike, ],
      [void],
      'nonpayable'
    >



    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >



    withdrawOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >



    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelBorrowRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'capacityManager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'createBorrowRequest'): TypedContractMethod<
      [amount: BigNumberish, maxAprBps: BigNumberish, maxDuration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createLenderOffer'): TypedContractMethod<
      [requestId: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, requiredCollateral: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'eligibilityRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getBorrowRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [BorrowRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getLenderOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [LenderOfferStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOpenRequests'): TypedContractMethod<
      [],
      [BorrowRequestStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'loanVault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nextOfferId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextRequestId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'offerDeposits'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'offers'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, string, bigint, bigint, bigint, bigint, bigint] & {offerId: bigint, requestId: bigint, lender: string, aprBps: bigint, duration: bigint, requiredCollateral: bigint, status: bigint, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, bigint, bigint, bigint, bigint, bigint, bigint] & {requestId: bigint, borrower: string, amount: bigint, maxAprBps: bigint, maxDuration: bigint, collateralAmount: bigint, status: bigint, createdAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'setLoanVault'): TypedContractMethod<
      [_loanVault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OfferAccepted'): TypedContractEvent<OfferAcceptedEvent.InputTuple, OfferAcceptedEvent.OutputTuple, OfferAcceptedEvent.OutputObject>;
getEvent(key: 'OfferCreated'): TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
getEvent(key: 'OfferWithdrawn'): TypedContractEvent<OfferWithdrawnEvent.InputTuple, OfferWithdrawnEvent.OutputTuple, OfferWithdrawnEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'RequestCancelled'): TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
getEvent(key: 'RequestCreated'): TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {

      'OfferAccepted(uint256,uint256)': TypedContractEvent<OfferAcceptedEvent.InputTuple, OfferAcceptedEvent.OutputTuple, OfferAcceptedEvent.OutputObject>;
      OfferAccepted: TypedContractEvent<OfferAcceptedEvent.InputTuple, OfferAcceptedEvent.OutputTuple, OfferAcceptedEvent.OutputObject>;


      'OfferCreated(uint256,uint256,address)': TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
      OfferCreated: TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;


      'OfferWithdrawn(uint256)': TypedContractEvent<OfferWithdrawnEvent.InputTuple, OfferWithdrawnEvent.OutputTuple, OfferWithdrawnEvent.OutputObject>;
      OfferWithdrawn: TypedContractEvent<OfferWithdrawnEvent.InputTuple, OfferWithdrawnEvent.OutputTuple, OfferWithdrawnEvent.OutputObject>;


      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;


      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;


      'RequestCancelled(uint256)': TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
      RequestCancelled: TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;


      'RequestCreated(uint256,address,uint256)': TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
      RequestCreated: TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;


      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    };
  }