/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type ArtefactStruct = {artefactId: BytesLike, creator: AddressLike, snapshotCommitment: BytesLike, eligibilityNonce: BigNumberish, policyReference: BytesLike, timestamp: BigNumberish, contentReference: string}

    export type ArtefactStructOutput = [artefactId: string, creator: string, snapshotCommitment: string, eligibilityNonce: bigint, policyReference: string, timestamp: bigint, contentReference: string] & {artefactId: string, creator: string, snapshotCommitment: string, eligibilityNonce: bigint, policyReference: string, timestamp: bigint, contentReference: string }
  

  export interface IArtefactRegistryInterface extends Interface {
    getFunction(nameOrSignature: "commitArtefact" | "getArtefact" | "getArtefactsByCreator" | "verifyArtefact"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ArtefactCommitted" | "ArtefactVerified"): EventFragment;

    encodeFunctionData(functionFragment: 'commitArtefact', values: [BytesLike, BigNumberish, BytesLike, string]): string;
encodeFunctionData(functionFragment: 'getArtefact', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getArtefactsByCreator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifyArtefact', values: [BytesLike, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'commitArtefact', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArtefact', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getArtefactsByCreator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyArtefact', data: BytesLike): Result;
  }

  
    export namespace ArtefactCommittedEvent {
      export type InputTuple = [artefactId: BytesLike, creator: AddressLike, snapshotCommitment: BytesLike];
      export type OutputTuple = [artefactId: string, creator: string, snapshotCommitment: string];
      export interface OutputObject {artefactId: string, creator: string, snapshotCommitment: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ArtefactVerifiedEvent {
      export type InputTuple = [artefactId: BytesLike, status: BigNumberish];
      export type OutputTuple = [artefactId: string, status: bigint];
      export interface OutputObject {artefactId: string, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IArtefactRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IArtefactRegistry;
    waitForDeployment(): Promise<this>;

    interface: IArtefactRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    commitArtefact: TypedContractMethod<
      [snapshotCommitment: BytesLike, eligibilityNonce: BigNumberish, policyReference: BytesLike, contentReference: string, ],
      [void],
      'nonpayable'
    >
    

    
    getArtefact: TypedContractMethod<
      [artefactId: BytesLike, ],
      [ArtefactStructOutput],
      'view'
    >
    

    
    getArtefactsByCreator: TypedContractMethod<
      [creator: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    verifyArtefact: TypedContractMethod<
      [artefactId: BytesLike, snapshotCommitment: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'commitArtefact'): TypedContractMethod<
      [snapshotCommitment: BytesLike, eligibilityNonce: BigNumberish, policyReference: BytesLike, contentReference: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getArtefact'): TypedContractMethod<
      [artefactId: BytesLike, ],
      [ArtefactStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getArtefactsByCreator'): TypedContractMethod<
      [creator: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'verifyArtefact'): TypedContractMethod<
      [artefactId: BytesLike, snapshotCommitment: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'ArtefactCommitted'): TypedContractEvent<ArtefactCommittedEvent.InputTuple, ArtefactCommittedEvent.OutputTuple, ArtefactCommittedEvent.OutputObject>;
getEvent(key: 'ArtefactVerified'): TypedContractEvent<ArtefactVerifiedEvent.InputTuple, ArtefactVerifiedEvent.OutputTuple, ArtefactVerifiedEvent.OutputObject>;

    filters: {
      
      'ArtefactCommitted(bytes32,address,bytes32)': TypedContractEvent<ArtefactCommittedEvent.InputTuple, ArtefactCommittedEvent.OutputTuple, ArtefactCommittedEvent.OutputObject>;
      ArtefactCommitted: TypedContractEvent<ArtefactCommittedEvent.InputTuple, ArtefactCommittedEvent.OutputTuple, ArtefactCommittedEvent.OutputObject>;
    

      'ArtefactVerified(bytes32,uint8)': TypedContractEvent<ArtefactVerifiedEvent.InputTuple, ArtefactVerifiedEvent.OutputTuple, ArtefactVerifiedEvent.OutputObject>;
      ArtefactVerified: TypedContractEvent<ArtefactVerifiedEvent.InputTuple, ArtefactVerifiedEvent.OutputTuple, ArtefactVerifiedEvent.OutputObject>;
    
    };
  }