/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IDebtAuctionManager {
      
    export type DebtAuctionStruct = {auctionId: BigNumberish, loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish, collateralAmount: BigNumberish, reservePrice: BigNumberish, highestBid: BigNumberish, highestBidder: AddressLike, startTime: BigNumberish, endTime: BigNumberish, status: BigNumberish}

    export type DebtAuctionStructOutput = [auctionId: bigint, loanId: bigint, borrower: string, lender: string, principal: bigint, collateralAmount: bigint, reservePrice: bigint, highestBid: bigint, highestBidder: string, startTime: bigint, endTime: bigint, status: bigint] & {auctionId: bigint, loanId: bigint, borrower: string, lender: string, principal: bigint, collateralAmount: bigint, reservePrice: bigint, highestBid: bigint, highestBidder: string, startTime: bigint, endTime: bigint, status: bigint }
  
    }

  export interface IDebtAuctionManagerInterface extends Interface {
    getFunction(nameOrSignature: "createAuction" | "getAuction" | "placeBid" | "settleAuction"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuctionCancelled" | "AuctionCreated" | "AuctionSettled" | "BidPlaced"): EventFragment;

    encodeFunctionData(functionFragment: 'createAuction', values: [BigNumberish, AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAuction', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'placeBid', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleAuction', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuction', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'placeBid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleAuction', data: BytesLike): Result;
  }

  
    export namespace AuctionCancelledEvent {
      export type InputTuple = [auctionId: BigNumberish];
      export type OutputTuple = [auctionId: bigint];
      export interface OutputObject {auctionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionCreatedEvent {
      export type InputTuple = [auctionId: BigNumberish, loanId: BigNumberish, lender: AddressLike, principal: BigNumberish, reservePrice: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [auctionId: bigint, loanId: bigint, lender: string, principal: bigint, reservePrice: bigint, endTime: bigint];
      export interface OutputObject {auctionId: bigint, loanId: bigint, lender: string, principal: bigint, reservePrice: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace AuctionSettledEvent {
      export type InputTuple = [auctionId: BigNumberish, winner: AddressLike, winningBid: BigNumberish, lenderPayout: BigNumberish, collateralClaimed: BigNumberish];
      export type OutputTuple = [auctionId: bigint, winner: string, winningBid: bigint, lenderPayout: bigint, collateralClaimed: bigint];
      export interface OutputObject {auctionId: bigint, winner: string, winningBid: bigint, lenderPayout: bigint, collateralClaimed: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BidPlacedEvent {
      export type InputTuple = [auctionId: BigNumberish, bidder: AddressLike, amount: BigNumberish];
      export type OutputTuple = [auctionId: bigint, bidder: string, amount: bigint];
      export interface OutputObject {auctionId: bigint, bidder: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IDebtAuctionManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): IDebtAuctionManager;
    waitForDeployment(): Promise<this>;

    interface: IDebtAuctionManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createAuction: TypedContractMethod<
      [loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish, collateralAmount: BigNumberish, reservePrice: BigNumberish, duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    getAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [IDebtAuctionManager.DebtAuctionStructOutput],
      'view'
    >
    

    
    placeBid: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    settleAuction: TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createAuction'): TypedContractMethod<
      [loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish, collateralAmount: BigNumberish, reservePrice: BigNumberish, duration: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [IDebtAuctionManager.DebtAuctionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'placeBid'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'settleAuction'): TypedContractMethod<
      [auctionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuctionCancelled'): TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
getEvent(key: 'AuctionCreated'): TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
getEvent(key: 'AuctionSettled'): TypedContractEvent<AuctionSettledEvent.InputTuple, AuctionSettledEvent.OutputTuple, AuctionSettledEvent.OutputObject>;
getEvent(key: 'BidPlaced'): TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;

    filters: {
      
      'AuctionCancelled(uint256)': TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
      AuctionCancelled: TypedContractEvent<AuctionCancelledEvent.InputTuple, AuctionCancelledEvent.OutputTuple, AuctionCancelledEvent.OutputObject>;
    

      'AuctionCreated(uint256,uint256,address,uint256,uint256,uint256)': TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
      AuctionCreated: TypedContractEvent<AuctionCreatedEvent.InputTuple, AuctionCreatedEvent.OutputTuple, AuctionCreatedEvent.OutputObject>;
    

      'AuctionSettled(uint256,address,uint256,uint256,uint256)': TypedContractEvent<AuctionSettledEvent.InputTuple, AuctionSettledEvent.OutputTuple, AuctionSettledEvent.OutputObject>;
      AuctionSettled: TypedContractEvent<AuctionSettledEvent.InputTuple, AuctionSettledEvent.OutputTuple, AuctionSettledEvent.OutputObject>;
    

      'BidPlaced(uint256,address,uint256)': TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
      BidPlaced: TypedContractEvent<BidPlacedEvent.InputTuple, BidPlacedEvent.OutputTuple, BidPlacedEvent.OutputObject>;
    
    };
  }