/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
    export type LoanStruct = {loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish, aprBps: BigNumberish, startTime: BigNumberish, duration: BigNumberish, collateralAmount: BigNumberish, repaidAmount: BigNumberish, status: BigNumberish}

    export type LoanStructOutput = [loanId: bigint, borrower: string, lender: string, principal: bigint, aprBps: bigint, startTime: bigint, duration: bigint, collateralAmount: bigint, repaidAmount: bigint, status: bigint] & {loanId: bigint, borrower: string, lender: string, principal: bigint, aprBps: bigint, startTime: bigint, duration: bigint, collateralAmount: bigint, repaidAmount: bigint, status: bigint }
  

  export interface ILoanVaultInterface extends Interface {
    getFunction(nameOrSignature: "calculateInterest" | "calculateTotalOwed" | "declareDefault" | "getLoan" | "originateLoan" | "repayLoan"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CollateralSeized" | "LoanDefaulted" | "LoanOriginated" | "LoanRepaid"): EventFragment;

    encodeFunctionData(functionFragment: 'calculateInterest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateTotalOwed', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'declareDefault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLoan', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'originateLoan', values: [AddressLike, AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'repayLoan', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'calculateInterest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateTotalOwed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'declareDefault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'originateLoan', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'repayLoan', data: BytesLike): Result;
  }

  
    export namespace CollateralSeizedEvent {
      export type InputTuple = [loanId: BigNumberish, lender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, lender: string, amount: bigint];
      export interface OutputObject {loanId: bigint, lender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanDefaultedEvent {
      export type InputTuple = [loanId: BigNumberish];
      export type OutputTuple = [loanId: bigint];
      export interface OutputObject {loanId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanOriginatedEvent {
      export type InputTuple = [loanId: BigNumberish, borrower: AddressLike, lender: AddressLike, principal: BigNumberish];
      export type OutputTuple = [loanId: bigint, borrower: string, lender: string, principal: bigint];
      export interface OutputObject {loanId: bigint, borrower: string, lender: string, principal: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LoanRepaidEvent {
      export type InputTuple = [loanId: BigNumberish, amount: BigNumberish];
      export type OutputTuple = [loanId: bigint, amount: bigint];
      export interface OutputObject {loanId: bigint, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ILoanVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILoanVault;
    waitForDeployment(): Promise<this>;

    interface: ILoanVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateInterest: TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calculateTotalOwed: TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    declareDefault: TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [LoanStructOutput],
      'view'
    >
    

    
    originateLoan: TypedContractMethod<
      [borrower: AddressLike, lender: AddressLike, principal: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'payable'
    >
    

    
    repayLoan: TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateInterest'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateTotalOwed'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'declareDefault'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [LoanStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'originateLoan'): TypedContractMethod<
      [borrower: AddressLike, lender: AddressLike, principal: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'repayLoan'): TypedContractMethod<
      [loanId: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'CollateralSeized'): TypedContractEvent<CollateralSeizedEvent.InputTuple, CollateralSeizedEvent.OutputTuple, CollateralSeizedEvent.OutputObject>;
getEvent(key: 'LoanDefaulted'): TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
getEvent(key: 'LoanOriginated'): TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
getEvent(key: 'LoanRepaid'): TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;

    filters: {
      
      'CollateralSeized(uint256,address,uint256)': TypedContractEvent<CollateralSeizedEvent.InputTuple, CollateralSeizedEvent.OutputTuple, CollateralSeizedEvent.OutputObject>;
      CollateralSeized: TypedContractEvent<CollateralSeizedEvent.InputTuple, CollateralSeizedEvent.OutputTuple, CollateralSeizedEvent.OutputObject>;
    

      'LoanDefaulted(uint256)': TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
      LoanDefaulted: TypedContractEvent<LoanDefaultedEvent.InputTuple, LoanDefaultedEvent.OutputTuple, LoanDefaultedEvent.OutputObject>;
    

      'LoanOriginated(uint256,address,address,uint256)': TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
      LoanOriginated: TypedContractEvent<LoanOriginatedEvent.InputTuple, LoanOriginatedEvent.OutputTuple, LoanOriginatedEvent.OutputObject>;
    

      'LoanRepaid(uint256,uint256)': TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
      LoanRepaid: TypedContractEvent<LoanRepaidEvent.InputTuple, LoanRepaidEvent.OutputTuple, LoanRepaidEvent.OutputObject>;
    
    };
  }