/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"

    export type BorrowRequestStruct = {requestId: BigNumberish, borrower: AddressLike, amount: BigNumberish, maxAprBps: BigNumberish, maxDuration: BigNumberish, collateralAmount: BigNumberish, status: BigNumberish, createdAt: BigNumberish}

    export type BorrowRequestStructOutput = [requestId: bigint, borrower: string, amount: bigint, maxAprBps: bigint, maxDuration: bigint, collateralAmount: bigint, status: bigint, createdAt: bigint] & {requestId: bigint, borrower: string, amount: bigint, maxAprBps: bigint, maxDuration: bigint, collateralAmount: bigint, status: bigint, createdAt: bigint }


    export type LenderOfferStruct = {offerId: BigNumberish, requestId: BigNumberish, lender: AddressLike, aprBps: BigNumberish, duration: BigNumberish, requiredCollateral: BigNumberish, status: BigNumberish, createdAt: BigNumberish}

    export type LenderOfferStructOutput = [offerId: bigint, requestId: bigint, lender: string, aprBps: bigint, duration: bigint, requiredCollateral: bigint, status: bigint, createdAt: bigint] & {offerId: bigint, requestId: bigint, lender: string, aprBps: bigint, duration: bigint, requiredCollateral: bigint, status: bigint, createdAt: bigint }


  export interface ILoanMarketplaceInterface extends Interface {
    getFunction(nameOrSignature: "acceptOffer" | "cancelBorrowRequest" | "createBorrowRequest" | "createLenderOffer" | "getBorrowRequest" | "getLenderOffer" | "getOpenRequests" | "withdrawOffer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OfferAccepted" | "OfferCreated" | "OfferWithdrawn" | "RequestCancelled" | "RequestCreated"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOffer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelBorrowRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createBorrowRequest', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'createLenderOffer', values: [BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getBorrowRequest', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getLenderOffer', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getOpenRequests', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawOffer', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acceptOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelBorrowRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createBorrowRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createLenderOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getBorrowRequest', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getLenderOffer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOpenRequests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawOffer', data: BytesLike): Result;
  }


    export namespace OfferAcceptedEvent {
      export type InputTuple = [offerId: BigNumberish, requestId: BigNumberish];
      export type OutputTuple = [offerId: bigint, requestId: bigint];
      export interface OutputObject {offerId: bigint, requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace OfferCreatedEvent {
      export type InputTuple = [offerId: BigNumberish, requestId: BigNumberish, lender: AddressLike];
      export type OutputTuple = [offerId: bigint, requestId: bigint, lender: string];
      export interface OutputObject {offerId: bigint, requestId: bigint, lender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace OfferWithdrawnEvent {
      export type InputTuple = [offerId: BigNumberish];
      export type OutputTuple = [offerId: bigint];
      export interface OutputObject {offerId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace RequestCancelledEvent {
      export type InputTuple = [requestId: BigNumberish];
      export type OutputTuple = [requestId: bigint];
      export interface OutputObject {requestId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



    export namespace RequestCreatedEvent {
      export type InputTuple = [requestId: BigNumberish, borrower: AddressLike, amount: BigNumberish];
      export type OutputTuple = [requestId: bigint, borrower: string, amount: bigint];
      export interface OutputObject {requestId: bigint, borrower: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }



  export interface ILoanMarketplace extends BaseContract {

    connect(runner?: ContractRunner | null): ILoanMarketplace;
    waitForDeployment(): Promise<this>;

    interface: ILoanMarketplaceInterface;


  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>




    acceptOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'payable'
    >



    cancelBorrowRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >



    createBorrowRequest: TypedContractMethod<
      [amount: BigNumberish, maxAprBps: BigNumberish, maxDuration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >



    createLenderOffer: TypedContractMethod<
      [requestId: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, requiredCollateral: BigNumberish, ],
      [bigint],
      'payable'
    >



    getBorrowRequest: TypedContractMethod<
      [requestId: BigNumberish, ],
      [BorrowRequestStructOutput],
      'view'
    >



    getLenderOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [LenderOfferStructOutput],
      'view'
    >



    getOpenRequests: TypedContractMethod<
      [],
      [BorrowRequestStructOutput[]],
      'view'
    >



    withdrawOffer: TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >



    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'cancelBorrowRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createBorrowRequest'): TypedContractMethod<
      [amount: BigNumberish, maxAprBps: BigNumberish, maxDuration: BigNumberish, collateralAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createLenderOffer'): TypedContractMethod<
      [requestId: BigNumberish, aprBps: BigNumberish, duration: BigNumberish, requiredCollateral: BigNumberish, ],
      [bigint],
      'payable'
    >;
getFunction(nameOrSignature: 'getBorrowRequest'): TypedContractMethod<
      [requestId: BigNumberish, ],
      [BorrowRequestStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getLenderOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [LenderOfferStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getOpenRequests'): TypedContractMethod<
      [],
      [BorrowRequestStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawOffer'): TypedContractMethod<
      [offerId: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OfferAccepted'): TypedContractEvent<OfferAcceptedEvent.InputTuple, OfferAcceptedEvent.OutputTuple, OfferAcceptedEvent.OutputObject>;
getEvent(key: 'OfferCreated'): TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
getEvent(key: 'OfferWithdrawn'): TypedContractEvent<OfferWithdrawnEvent.InputTuple, OfferWithdrawnEvent.OutputTuple, OfferWithdrawnEvent.OutputObject>;
getEvent(key: 'RequestCancelled'): TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
getEvent(key: 'RequestCreated'): TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;

    filters: {

      'OfferAccepted(uint256,uint256)': TypedContractEvent<OfferAcceptedEvent.InputTuple, OfferAcceptedEvent.OutputTuple, OfferAcceptedEvent.OutputObject>;
      OfferAccepted: TypedContractEvent<OfferAcceptedEvent.InputTuple, OfferAcceptedEvent.OutputTuple, OfferAcceptedEvent.OutputObject>;


      'OfferCreated(uint256,uint256,address)': TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;
      OfferCreated: TypedContractEvent<OfferCreatedEvent.InputTuple, OfferCreatedEvent.OutputTuple, OfferCreatedEvent.OutputObject>;


      'OfferWithdrawn(uint256)': TypedContractEvent<OfferWithdrawnEvent.InputTuple, OfferWithdrawnEvent.OutputTuple, OfferWithdrawnEvent.OutputObject>;
      OfferWithdrawn: TypedContractEvent<OfferWithdrawnEvent.InputTuple, OfferWithdrawnEvent.OutputTuple, OfferWithdrawnEvent.OutputObject>;


      'RequestCancelled(uint256)': TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;
      RequestCancelled: TypedContractEvent<RequestCancelledEvent.InputTuple, RequestCancelledEvent.OutputTuple, RequestCancelledEvent.OutputObject>;


      'RequestCreated(uint256,address,uint256)': TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;
      RequestCreated: TypedContractEvent<RequestCreatedEvent.InputTuple, RequestCreatedEvent.OutputTuple, RequestCreatedEvent.OutputObject>;

    };
  }