/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../../common.js"
  import type { MockAcceptingVerifier, MockAcceptingVerifierInterface } from "../../../test/MockNativeQueryVerifier.sol/MockAcceptingVerifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "uint64",
        "name": "",
        "type": "uint64"
      },
      {
        "internalType": "bytes",
        "name": "",
        "type": "bytes"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "root",
            "type": "bytes32"
          },
          {
            "components": [
              {
                "internalType": "bytes32",
                "name": "hash",
                "type": "bytes32"
              },
              {
                "internalType": "bool",
                "name": "isLeft",
                "type": "bool"
              }
            ],
            "internalType": "struct INativeQueryVerifier.MerkleProofEntry[]",
            "name": "siblings",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct INativeQueryVerifier.MerkleProof",
        "name": "",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "bytes32",
            "name": "lowerEndpointDigest",
            "type": "bytes32"
          },
          {
            "internalType": "bytes32[]",
            "name": "roots",
            "type": "bytes32[]"
          }
        ],
        "internalType": "struct INativeQueryVerifier.ContinuityProof",
        "name": "",
        "type": "tuple"
      }
    ],
    "name": "verify",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x608080604052346100155760e3908161001a8239f35b5f80fdfe60808060405260043610156011575f80fd5b5f3560e01c637cc4e258146023575f80fd5b3460a95760031960a03682011260a95767ffffffffffffffff906004358281160360a9576024358281160360a95760443582811160a9573660238201121560a957806004013583811160a9573691016024011160a95760643582811160a957816040913603011260a95760843591821160a9576040913603011260a95780600160209252f35b5f80fdfea264697066735822122050f1859a9031d29050e34840bcdb715c925853dfc80af9c1a67c740996b90f6f64736f6c63430008170033";

  
      type MockAcceptingVerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockAcceptingVerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockAcceptingVerifier__factory extends ContractFactory {
    
      constructor(...args: MockAcceptingVerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockAcceptingVerifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockAcceptingVerifier__factory {
      return super.connect(runner) as MockAcceptingVerifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockAcceptingVerifierInterface {
      return new Interface(_abi) as MockAcceptingVerifierInterface;
    }
    
    override attach(address: string | Addressable): MockAcceptingVerifier {
      return super.attach(address) as MockAcceptingVerifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockAcceptingVerifier {
      return new Contract(address, _abi, runner) as unknown as MockAcceptingVerifier;
    }
  }

  
  